### ISSUE TITLE
Continuation of the project

### ISSUE THREAD

**Issue by lewisje** [hintjens/scalable-c#13]
I just read [on your blog](http://hintjens.com/blog:115) that you are near death, and now I wonder whom, if anyone, you have contacted about finishing this book, or at least giving the unfinished version a proper release.

In case you were wondering, I'm not qualified to work on this, knowing little about C programming or scalability myself.

**Comment by hintjens** [comment]
I'll sketch out each chapter and spend a few days working on it, still. May not be pretty but I might be able to get the core done.

**Comment by vb-mich** [comment]
"The C language is small and yet it takes years to master it. I wrote this book to speed people along that path"

The world needs this knowledge, keep on going!

**Comment by hintjens** [comment]
I will write more starting next week...

**Comment by mehdisadeghi** [comment]
@hintjens Thank you for whatever you have written so far ( I have been reading this book for a while now), please spend your precious time with your kids and loved ones.

**Comment by Thelordchosen** [comment]
this is 2023 and read the above comments with tears in my eyes. Humans are at our core Good
