### ISSUE TITLE
Problem: format not recognized by gitbook.

### ISSUE THREAD

**Issue by ghost** [hintjens/scalable-c#3]
Makes it difficult to correct formatting errors since we cannot see rendered content.
Ex: 

![screen shot 2016-01-16 at 23 21 33](https://cloud.githubusercontent.com/assets/10885649/12374802/eb0782e4-bca7-11e5-865a-cc0679b58547.png)

A blanck line is missing somewhere probably...

**Comment by hintjens** [comment]
Indeed, a blank line is missing. I'm sorry the source isn't on gitbook. Maybe I can make that work in the future. Thanks for this fix.
